AllCops:
   Exclude:
     - 'node_modules/**/*'
     - 'vendor/**/*'
     - '.git/**/*'
     - 'review_apps/**/*'

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false  
