---
version: '2'
services:
  db:
    image: openbuildservice/mariadb
  cache:
    image: openbuildservice/memcached
  backend:
    image: openbuildservice/backend
    volumes:
    - ".:/obs"
  worker:
    image: openbuildservice/backend
    volumes:
    - ".:/obs"
    privileged: true
    depends_on:
    - backend
    command: "/obs/contrib/start_development_worker"
  frontend:
    image: openbuildservice/frontend
    networks:
    - traefik
    - default
    build:
      dockerfile: docker-files/Dockerfile
      context: src/api
    command: "/obs/contrib/entrypoint.sh"
    volumes:
    - ".:/obs"
    environment:
    labels:
      traefik.frontend.rule: to-be-replaced
      traefik.docker.network: traefik_default
      traefik.port: '3000'
    depends_on:
    - db
    - cache
    - backend
    - worker
networks:
  traefik:
    external:
      name: traefik_default
